<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJSB0MuX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJSB0MuX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJSB0MuX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJSB0MuX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJSB0MuX\App_KernelDevDebugContainer([
    'container.build_hash' => 'JSB0MuX',
    'container.build_id' => '5116a732',
    'container.build_time' => 1785163839,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJSB0MuX');
